<?php

namespace Database\Seeders;

use App\Card;
use App\Course;
use App\Enums\EnrollmentRole;
use App\Enums\TranscriptionType;
use App\State;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

/**
 * Seed a course big enough to measure the performance of the finder.
 *
 * This seeder is not part of DatabaseSeeder, it only adds a course and leaves
 * the rest of the database untouched. Run it with:
 *
 *   php artisan db:seed --class=PerformanceTableSeeder
 *
 * Rows are inserted in bulk, which bypasses the model events: every column the
 * observers would fill (the position of a card, its state) is set here.
 */
class PerformanceTableSeeder extends Seeder
{
    /**
     * Number of cards spread over the course.
     */
    const CARDS = 1000;

    /**
     * Number of folders at the root, and per level below it.
     */
    const ROOT_FOLDERS = 12;

    const CHILD_FOLDERS = 3;

    const GRAND_CHILD_FOLDERS = 2;

    /**
     * Number of users enrolled in the course, managers included.
     */
    const USERS = 150;

    const MANAGERS = 5;

    /**
     * Number of users whose account is expired. They are taken from the end of
     * the list, so that the managers keep a valid account.
     */
    const EXPIRED_USERS = 8;

    /**
     * Number of tags of the course.
     */
    const TAGS = 30;

    /**
     * Number of holders a card is assigned to, at most.
     */
    const HOLDERS_PER_CARD = 3;

    /**
     * Number of rows inserted per query.
     */
    const CHUNK = 500;

    private Carbon $now;

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $this->now = Carbon::now();

        // The observer of the course creates its states.
        $course = Course::create([
            'name' => 'Performance test space '.$this->now->format('Y-m-d H:i'),
            'description' => 'Generated by PerformanceTableSeeder.',
            'transcription' => TranscriptionType::Icor,
        ]);

        $states = State::where('course_id', $course->id)->pluck('id');
        $tags = $this->createTags($course);
        $folders = $this->createFolders($course);
        $cards = $this->createCards($course, $folders, $states);

        $this->attachTags($cards, $tags);
        $this->enrollUsers($course, $cards);

        $this->command->info(
            "Seeded course #{$course->id} \"{$course->name}\" with "
            .$cards->count().' cards, '
            .$folders->count().' folders, '
            .static::USERS.' users, '
            .$tags->count().' tags.'
        );
        $this->command->info('URL: '.route('courses.show', $course->id));
    }

    /**
     * Create the tags of the course and return their ids.
     */
    private function createTags(Course $course): Collection
    {
        $rows = collect(range(1, static::TAGS))->map(fn ($i) => [
            'name' => 'perf-tag-'.$i,
            'course_id' => $course->id,
            'created_at' => $this->now,
            'updated_at' => $this->now,
        ]);

        DB::table('tags')->insert($rows->all());

        return DB::table('tags')->where('course_id', $course->id)->pluck('id');
    }

    /**
     * Create three levels of folders and return all their ids.
     */
    private function createFolders(Course $course): Collection
    {
        $roots = $this->insertFolders($course, [null], static::ROOT_FOLDERS);
        $children = $this->insertFolders($course, $roots->all(), static::CHILD_FOLDERS);
        $grandChildren = $this->insertFolders($course, $children->all(), static::GRAND_CHILD_FOLDERS);

        return $roots->concat($children)->concat($grandChildren);
    }

    /**
     * Create $count folders under each given parent and return the ids of the
     * folders that were just created.
     */
    private function insertFolders(Course $course, array $parents, int $count): Collection
    {
        $known = DB::table('folders')->where('course_id', $course->id)->pluck('id');

        $rows = collect($parents)->flatMap(
            fn ($parent) => collect(range(1, $count))->map(fn ($position) => [
                'title' => 'Folder '.fake()->words(2, true),
                'position' => $position - 1,
                'course_id' => $course->id,
                'parent_id' => $parent,
                'created_at' => $this->now,
                'updated_at' => $this->now,
            ])
        );

        foreach ($rows->chunk(static::CHUNK) as $chunk) {
            DB::table('folders')->insert($chunk->values()->all());
        }

        return DB::table('folders')
            ->where('course_id', $course->id)
            ->whereNotIn('id', $known)
            ->pluck('id');
    }

    /**
     * Spread the cards over the root of the course and its folders, and return
     * their ids.
     */
    private function createCards(
        Course $course,
        Collection $folders,
        Collection $states,
    ): Collection {
        // The root of the course holds cards too.
        $parents = $folders->concat([null]);

        // Keep the position of the cards sequential inside their parent.
        $positions = [];

        $rows = collect(range(1, static::CARDS))->map(function ($i) use ($course, $parents, $states, &$positions) {
            $parent = $parents->random();
            $key = $parent ?? 0;
            $positions[$key] = ($positions[$key] ?? -1) + 1;

            return [
                'title' => Str::ucfirst(fake()->words(rand(2, 6), true)),
                'box2' => $this->transcription(),
                'box3' => '<p>'.fake()->paragraph().'</p>',
                'box4' => '<p>'.fake()->paragraph().'</p>',
                'course_id' => $course->id,
                'folder_id' => $parent,
                'state_id' => $states->random(),
                'position' => $positions[$key],
                'options' => Card::OPTIONS,
                'created_at' => $this->now,
                'updated_at' => $this->now,
            ];
        });

        foreach ($rows->chunk(static::CHUNK) as $chunk) {
            DB::table('cards')->insert($chunk->values()->all());
        }

        return DB::table('cards')->where('course_id', $course->id)->pluck('id');
    }

    /**
     * Build an ICOR transcription, the speaker being at most 3 characters and
     * the speech at most Card::MAX_CHARACTERS_SPEECH.
     */
    private function transcription(): string
    {
        $lines = collect(range(1, rand(3, 12)))->map(fn ($number) => [
            'number' => $number,
            'speaker' => Str::upper(Str::substr(fake()->firstName(), 0, 3)),
            'speech' => Str::substr(fake()->sentence(), 0, Card::MAX_CHARACTERS_SPEECH),
            'linkedToPrevious' => false,
        ]);

        return json_encode([
            'version' => 2,
            TranscriptionType::Icor => $lines->all(),
            TranscriptionType::Text => null,
        ]);
    }

    /**
     * Attach a few tags to each card.
     */
    private function attachTags(Collection $cards, Collection $tags): void
    {
        $rows = $cards->flatMap(
            fn ($card) => $tags->random(rand(0, 4))->map(fn ($tag) => [
                'card_id' => $card,
                'tag_id' => $tag,
                'created_at' => $this->now,
                'updated_at' => $this->now,
            ])
        );

        foreach ($rows->chunk(static::CHUNK) as $chunk) {
            DB::table('card_tag')->insert($chunk->values()->all());
        }
    }

    /**
     * Create the users, enroll them in the course and assign the cards to them.
     */
    private function enrollUsers(Course $course, Collection $cards): void
    {
        // Hashing is slow, the users of a test course can share a password.
        $password = Hash::make('password');

        $rows = collect(range(1, static::USERS))->map(fn ($i) => [
            'name' => fake()->name(),
            'email' => "perf{$course->id}-user{$i}@example.com",
            'password' => $password,
            'remember_token' => Str::random(10),
            'validity' => $i > static::USERS - static::EXPIRED_USERS
                ? $this->now->copy()->subDays(rand(1, 90))
                : $this->now->copy()->addMonths(config('const.users.validity')),
            'created_at' => $this->now,
            'updated_at' => $this->now,
        ]);

        foreach ($rows->chunk(static::CHUNK) as $chunk) {
            DB::table('users')->insert($chunk->values()->all());
        }

        // Ordered by id, so that the first ones are the users inserted first:
        // the managers below are then never among the expired accounts.
        $users = DB::table('users')
            ->where('email', 'like', "perf{$course->id}-user%")
            ->orderBy('id')
            ->pluck('id');

        // Assign every card to a few holders, so that the enrollments carry
        // realistic lists of cards.
        $held = [];
        foreach ($cards as $card) {
            foreach ($users->random(rand(1, static::HOLDERS_PER_CARD)) as $user) {
                $held[$user][] = $card;
            }
        }

        $rows = $users->values()->map(fn ($user, $index) => [
            'role' => $index < static::MANAGERS
                ? EnrollmentRole::Manager
                : EnrollmentRole::Member,
            'course_id' => $course->id,
            'user_id' => $user,
            'cards' => json_encode($held[$user] ?? []),
            'created_at' => $this->now,
            'updated_at' => $this->now,
        ]);

        foreach ($rows->chunk(static::CHUNK) as $chunk) {
            DB::table('enrollments')->insert($chunk->values()->all());
        }
    }
}
